resources:
  - deployment.yaml
  - service.yaml
  - secrets.yaml

configMapGenerator:
  - name: env-vars
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: false  # Important: leave hash enabled so ArgoCD sees a diff

replacements:
  - source:
      kind: ConfigMap
      name: env-vars
      fieldPath: data.TAG
    targets:
      - select:
          kind: Deployment
          name: todo-app
        fieldPaths:
          - spec.template.spec.containers.[name=todo-app].image
        options:
          delimiter: ":"
          index: 1
