apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://yaramaher:Yy%40123%40maher@cluster0.6kgdens.mongodb.net/todolistDb"