---
- name: Configure target vm
  hosts: all
  become: yes
  vars_files:
    - vault.yaml

  tasks:

    - name: Install git
      yum:
        name: git
        state: present

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ansible user to docker group
      user:
        name: "ansible"
        groups: docker
        append: yes

    - name: Install pip3
      yum:
        name: python3-pip
        state: present

    - name: Install Docker Compose
      pip:
        name: docker-compose
        executable: pip3
        extra_args: --user

    - name: Docker login
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ docker_username }}"
        password: "{{ docker_token }}"