---
- name: Configure target vm
  hosts: targets
  become: yes
  vars_files:
    - vault.yaml

  tasks:

    - name: Install git
      yum:
        name: git
        state: present

    - name: Clone the repo
      git:
        repo: "https://github.com/Yaraa-Maher/ToDoApp.git"
        dest: "/home/ec2-user/todo-app"
        version: main
        update: yes

    - name: Set ownership to ec2-user
      file:
        path: "/home/ec2-user/todo-app"
        owner: ec2-user
        group: ec2-user
        recurse: yes

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ansible user to docker group
      user:
        name: "ansible"
        groups: docker
        append: yes

    - name: Ensure /usr/local/lib/docker/cli-plugins directory exists
      file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
        mode: '0755'
        recurse: yes

    - name: Download Docker Compose v2 binary
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: '0755'

    - name: Create symlink for backward-compatible 'docker-compose' command
      file:
        src: /usr/local/lib/docker/cli-plugins/docker-compose
        dest: /usr/local/bin/docker-compose
        state: link
        force: yes

    - name: Docker login
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ docker_username }}"
        password: "{{ docker_token }}"